name: Build ZMK Firmware

on:
  push:
    branches:
      - main  # Trigger on pushes to the `main` branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the `main` branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python (if ZMK tools use it)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install West (ZMK dependency)
      - name: Install West and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git cmake ninja-build gperf ccache dfu-util python3-pip python3-dev
          pip install west

      # Initialize and update the ZMK repository
      - name: Initialize ZMK
        run: |
          west init -l app
          west update

      # Build the firmware for a specific board
      - name: Build ZMK Firmware
        run: |
          west build -d build/my_board -b my_board -- -DSHIELD=my_shield
          
      # Upload the artifact (optional)
      - name: Upload Firmware
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: build/my_board/zephyr/zmk.uf2  # Adjust the path for your board's firmware
